name: Test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: test and build
        run: ./gradlew -Pversion="1.$(echo $GITHUB_SHA | cut -c1-7)" build
